/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface BlogPost {
  'id' : BlogPostId,
  'postType' : PostType,
  'title' : string,
  'featured' : boolean,
  'content' : string,
  'createdAt' : bigint,
  'slug' : string,
  'tags' : Array<string>,
  'imageUrl' : string,
  'projectId' : [] | [bigint],
  'excerpt' : string,
}
export type BlogPostId = bigint;
export interface BlogPostInput {
  'postType' : PostType,
  'title' : string,
  'featured' : boolean,
  'content' : string,
  'slug' : string,
  'tags' : Array<string>,
  'imageUrl' : string,
  'projectId' : [] | [bigint],
  'excerpt' : string,
}
export interface ContactInput {
  'service' : string,
  'name' : string,
  'email' : string,
  'projectDetails' : string,
}
export interface ContactSubmission {
  'id' : SubmissionId,
  'service' : string,
  'name' : string,
  'createdAt' : bigint,
  'email' : string,
  'projectDetails' : string,
}
export type PostType = { 'caseStudy' : null } |
  { 'standalone' : null };
export interface Project {
  'id' : ProjectId,
  'title' : string,
  'createdAt' : bigint,
  'description' : string,
  'imageUrl' : string,
  'category' : string,
  'techStack' : Array<string>,
}
export type ProjectId = bigint;
export interface ProjectInput {
  'title' : string,
  'description' : string,
  'imageUrl' : string,
  'category' : string,
  'techStack' : Array<string>,
}
export type SubmissionId = bigint;
export interface Testimonial {
  'id' : TestimonialId,
  'featured' : boolean,
  'clientName' : string,
  'createdAt' : bigint,
  'tags' : Array<string>,
  'quote' : string,
  'company' : string,
  'imageUrl' : string,
  'projectId' : [] | [bigint],
  'rating' : bigint,
  'clientTitle' : string,
}
export type TestimonialId = bigint;
export interface TestimonialInput {
  'featured' : boolean,
  'clientName' : string,
  'tags' : Array<string>,
  'quote' : string,
  'company' : string,
  'imageUrl' : string,
  'projectId' : [] | [bigint],
  'rating' : bigint,
  'clientTitle' : string,
}
export interface _SERVICE {
  'addBlogPost' : ActorMethod<
    [BlogPostInput],
    { 'ok' : BlogPost } |
      { 'err' : string }
  >,
  'addProject' : ActorMethod<[ProjectInput], Project>,
  'addTestimonial' : ActorMethod<
    [TestimonialInput],
    { 'ok' : Testimonial } |
      { 'err' : string }
  >,
  'deleteBlogPost' : ActorMethod<
    [bigint],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'deleteProject' : ActorMethod<[ProjectId], boolean>,
  'deleteSubmission' : ActorMethod<[SubmissionId], boolean>,
  'deleteTestimonial' : ActorMethod<
    [bigint],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'featureBlogPost' : ActorMethod<
    [bigint, boolean],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'featureTestimonial' : ActorMethod<
    [bigint, boolean],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'getBlogPost' : ActorMethod<[string], [] | [BlogPost]>,
  'getBlogPosts' : ActorMethod<[], Array<BlogPost>>,
  'getBlogPostsForProject' : ActorMethod<[bigint], Array<BlogPost>>,
  'getFeaturedBlogPosts' : ActorMethod<[], Array<BlogPost>>,
  'getFeaturedTestimonials' : ActorMethod<[], Array<Testimonial>>,
  'getProject' : ActorMethod<[ProjectId], [] | [Project]>,
  'getProjects' : ActorMethod<[], Array<Project>>,
  'getSubmissions' : ActorMethod<[], Array<ContactSubmission>>,
  'getTestimonials' : ActorMethod<[], Array<Testimonial>>,
  'getTestimonialsForProject' : ActorMethod<[bigint], Array<Testimonial>>,
  'isAdmin' : ActorMethod<[], boolean>,
  'submitContact' : ActorMethod<[ContactInput], ContactSubmission>,
  'updateBlogPost' : ActorMethod<
    [bigint, BlogPostInput],
    { 'ok' : BlogPost } |
      { 'err' : string }
  >,
  'updateProject' : ActorMethod<[ProjectId, ProjectInput], [] | [Project]>,
  'updateTestimonial' : ActorMethod<
    [bigint, TestimonialInput],
    { 'ok' : Testimonial } |
      { 'err' : string }
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];