/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const PostType = IDL.Variant({
  'caseStudy' : IDL.Null,
  'standalone' : IDL.Null,
});
export const BlogPostInput = IDL.Record({
  'postType' : PostType,
  'title' : IDL.Text,
  'featured' : IDL.Bool,
  'content' : IDL.Text,
  'slug' : IDL.Text,
  'tags' : IDL.Vec(IDL.Text),
  'imageUrl' : IDL.Text,
  'projectId' : IDL.Opt(IDL.Nat),
  'excerpt' : IDL.Text,
});
export const BlogPostId = IDL.Nat;
export const BlogPost = IDL.Record({
  'id' : BlogPostId,
  'postType' : PostType,
  'title' : IDL.Text,
  'featured' : IDL.Bool,
  'content' : IDL.Text,
  'createdAt' : IDL.Int,
  'slug' : IDL.Text,
  'tags' : IDL.Vec(IDL.Text),
  'imageUrl' : IDL.Text,
  'projectId' : IDL.Opt(IDL.Nat),
  'excerpt' : IDL.Text,
});
export const ProjectInput = IDL.Record({
  'title' : IDL.Text,
  'description' : IDL.Text,
  'imageUrl' : IDL.Text,
  'category' : IDL.Text,
  'techStack' : IDL.Vec(IDL.Text),
});
export const ProjectId = IDL.Nat;
export const Project = IDL.Record({
  'id' : ProjectId,
  'title' : IDL.Text,
  'createdAt' : IDL.Int,
  'description' : IDL.Text,
  'imageUrl' : IDL.Text,
  'category' : IDL.Text,
  'techStack' : IDL.Vec(IDL.Text),
});
export const TestimonialInput = IDL.Record({
  'featured' : IDL.Bool,
  'clientName' : IDL.Text,
  'tags' : IDL.Vec(IDL.Text),
  'quote' : IDL.Text,
  'company' : IDL.Text,
  'imageUrl' : IDL.Text,
  'projectId' : IDL.Opt(IDL.Nat),
  'rating' : IDL.Nat,
  'clientTitle' : IDL.Text,
});
export const TestimonialId = IDL.Nat;
export const Testimonial = IDL.Record({
  'id' : TestimonialId,
  'featured' : IDL.Bool,
  'clientName' : IDL.Text,
  'createdAt' : IDL.Int,
  'tags' : IDL.Vec(IDL.Text),
  'quote' : IDL.Text,
  'company' : IDL.Text,
  'imageUrl' : IDL.Text,
  'projectId' : IDL.Opt(IDL.Nat),
  'rating' : IDL.Nat,
  'clientTitle' : IDL.Text,
});
export const SubmissionId = IDL.Nat;
export const ContactSubmission = IDL.Record({
  'id' : SubmissionId,
  'service' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'email' : IDL.Text,
  'projectDetails' : IDL.Text,
});
export const ContactInput = IDL.Record({
  'service' : IDL.Text,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'projectDetails' : IDL.Text,
});

export const idlService = IDL.Service({
  'addBlogPost' : IDL.Func(
      [BlogPostInput],
      [IDL.Variant({ 'ok' : BlogPost, 'err' : IDL.Text })],
      [],
    ),
  'addProject' : IDL.Func([ProjectInput], [Project], []),
  'addTestimonial' : IDL.Func(
      [TestimonialInput],
      [IDL.Variant({ 'ok' : Testimonial, 'err' : IDL.Text })],
      [],
    ),
  'deleteBlogPost' : IDL.Func(
      [IDL.Nat],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'deleteProject' : IDL.Func([ProjectId], [IDL.Bool], []),
  'deleteSubmission' : IDL.Func([SubmissionId], [IDL.Bool], []),
  'deleteTestimonial' : IDL.Func(
      [IDL.Nat],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'featureBlogPost' : IDL.Func(
      [IDL.Nat, IDL.Bool],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'featureTestimonial' : IDL.Func(
      [IDL.Nat, IDL.Bool],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'getBlogPost' : IDL.Func([IDL.Text], [IDL.Opt(BlogPost)], ['query']),
  'getBlogPosts' : IDL.Func([], [IDL.Vec(BlogPost)], ['query']),
  'getBlogPostsForProject' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(BlogPost)],
      ['query'],
    ),
  'getFeaturedBlogPosts' : IDL.Func([], [IDL.Vec(BlogPost)], ['query']),
  'getFeaturedTestimonials' : IDL.Func([], [IDL.Vec(Testimonial)], ['query']),
  'getProject' : IDL.Func([ProjectId], [IDL.Opt(Project)], ['query']),
  'getProjects' : IDL.Func([], [IDL.Vec(Project)], ['query']),
  'getSubmissions' : IDL.Func([], [IDL.Vec(ContactSubmission)], ['query']),
  'getTestimonials' : IDL.Func([], [IDL.Vec(Testimonial)], ['query']),
  'getTestimonialsForProject' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(Testimonial)],
      ['query'],
    ),
  'isAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'submitContact' : IDL.Func([ContactInput], [ContactSubmission], []),
  'updateBlogPost' : IDL.Func(
      [IDL.Nat, BlogPostInput],
      [IDL.Variant({ 'ok' : BlogPost, 'err' : IDL.Text })],
      [],
    ),
  'updateProject' : IDL.Func([ProjectId, ProjectInput], [IDL.Opt(Project)], []),
  'updateTestimonial' : IDL.Func(
      [IDL.Nat, TestimonialInput],
      [IDL.Variant({ 'ok' : Testimonial, 'err' : IDL.Text })],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const PostType = IDL.Variant({
    'caseStudy' : IDL.Null,
    'standalone' : IDL.Null,
  });
  const BlogPostInput = IDL.Record({
    'postType' : PostType,
    'title' : IDL.Text,
    'featured' : IDL.Bool,
    'content' : IDL.Text,
    'slug' : IDL.Text,
    'tags' : IDL.Vec(IDL.Text),
    'imageUrl' : IDL.Text,
    'projectId' : IDL.Opt(IDL.Nat),
    'excerpt' : IDL.Text,
  });
  const BlogPostId = IDL.Nat;
  const BlogPost = IDL.Record({
    'id' : BlogPostId,
    'postType' : PostType,
    'title' : IDL.Text,
    'featured' : IDL.Bool,
    'content' : IDL.Text,
    'createdAt' : IDL.Int,
    'slug' : IDL.Text,
    'tags' : IDL.Vec(IDL.Text),
    'imageUrl' : IDL.Text,
    'projectId' : IDL.Opt(IDL.Nat),
    'excerpt' : IDL.Text,
  });
  const ProjectInput = IDL.Record({
    'title' : IDL.Text,
    'description' : IDL.Text,
    'imageUrl' : IDL.Text,
    'category' : IDL.Text,
    'techStack' : IDL.Vec(IDL.Text),
  });
  const ProjectId = IDL.Nat;
  const Project = IDL.Record({
    'id' : ProjectId,
    'title' : IDL.Text,
    'createdAt' : IDL.Int,
    'description' : IDL.Text,
    'imageUrl' : IDL.Text,
    'category' : IDL.Text,
    'techStack' : IDL.Vec(IDL.Text),
  });
  const TestimonialInput = IDL.Record({
    'featured' : IDL.Bool,
    'clientName' : IDL.Text,
    'tags' : IDL.Vec(IDL.Text),
    'quote' : IDL.Text,
    'company' : IDL.Text,
    'imageUrl' : IDL.Text,
    'projectId' : IDL.Opt(IDL.Nat),
    'rating' : IDL.Nat,
    'clientTitle' : IDL.Text,
  });
  const TestimonialId = IDL.Nat;
  const Testimonial = IDL.Record({
    'id' : TestimonialId,
    'featured' : IDL.Bool,
    'clientName' : IDL.Text,
    'createdAt' : IDL.Int,
    'tags' : IDL.Vec(IDL.Text),
    'quote' : IDL.Text,
    'company' : IDL.Text,
    'imageUrl' : IDL.Text,
    'projectId' : IDL.Opt(IDL.Nat),
    'rating' : IDL.Nat,
    'clientTitle' : IDL.Text,
  });
  const SubmissionId = IDL.Nat;
  const ContactSubmission = IDL.Record({
    'id' : SubmissionId,
    'service' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'email' : IDL.Text,
    'projectDetails' : IDL.Text,
  });
  const ContactInput = IDL.Record({
    'service' : IDL.Text,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'projectDetails' : IDL.Text,
  });
  
  return IDL.Service({
    'addBlogPost' : IDL.Func(
        [BlogPostInput],
        [IDL.Variant({ 'ok' : BlogPost, 'err' : IDL.Text })],
        [],
      ),
    'addProject' : IDL.Func([ProjectInput], [Project], []),
    'addTestimonial' : IDL.Func(
        [TestimonialInput],
        [IDL.Variant({ 'ok' : Testimonial, 'err' : IDL.Text })],
        [],
      ),
    'deleteBlogPost' : IDL.Func(
        [IDL.Nat],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'deleteProject' : IDL.Func([ProjectId], [IDL.Bool], []),
    'deleteSubmission' : IDL.Func([SubmissionId], [IDL.Bool], []),
    'deleteTestimonial' : IDL.Func(
        [IDL.Nat],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'featureBlogPost' : IDL.Func(
        [IDL.Nat, IDL.Bool],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'featureTestimonial' : IDL.Func(
        [IDL.Nat, IDL.Bool],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'getBlogPost' : IDL.Func([IDL.Text], [IDL.Opt(BlogPost)], ['query']),
    'getBlogPosts' : IDL.Func([], [IDL.Vec(BlogPost)], ['query']),
    'getBlogPostsForProject' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(BlogPost)],
        ['query'],
      ),
    'getFeaturedBlogPosts' : IDL.Func([], [IDL.Vec(BlogPost)], ['query']),
    'getFeaturedTestimonials' : IDL.Func([], [IDL.Vec(Testimonial)], ['query']),
    'getProject' : IDL.Func([ProjectId], [IDL.Opt(Project)], ['query']),
    'getProjects' : IDL.Func([], [IDL.Vec(Project)], ['query']),
    'getSubmissions' : IDL.Func([], [IDL.Vec(ContactSubmission)], ['query']),
    'getTestimonials' : IDL.Func([], [IDL.Vec(Testimonial)], ['query']),
    'getTestimonialsForProject' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(Testimonial)],
        ['query'],
      ),
    'isAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'submitContact' : IDL.Func([ContactInput], [ContactSubmission], []),
    'updateBlogPost' : IDL.Func(
        [IDL.Nat, BlogPostInput],
        [IDL.Variant({ 'ok' : BlogPost, 'err' : IDL.Text })],
        [],
      ),
    'updateProject' : IDL.Func(
        [ProjectId, ProjectInput],
        [IDL.Opt(Project)],
        [],
      ),
    'updateTestimonial' : IDL.Func(
        [IDL.Nat, TestimonialInput],
        [IDL.Variant({ 'ok' : Testimonial, 'err' : IDL.Text })],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };