/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Testimonial {
    id: TestimonialId;
    featured: boolean;
    clientName: string;
    createdAt: bigint;
    tags: Array<string>;
    quote: string;
    company: string;
    imageUrl: string;
    projectId?: bigint;
    rating: bigint;
    clientTitle: string;
}
export interface ContactInput {
    service: string;
    name: string;
    email: string;
    projectDetails: string;
}
export interface BlogPost {
    id: BlogPostId;
    postType: PostType;
    title: string;
    featured: boolean;
    content: string;
    createdAt: bigint;
    slug: string;
    tags: Array<string>;
    imageUrl: string;
    projectId?: bigint;
    excerpt: string;
}
export interface ProjectInput {
    title: string;
    description: string;
    imageUrl: string;
    category: string;
    techStack: Array<string>;
}
export type BlogPostId = bigint;
export interface ContactSubmission {
    id: SubmissionId;
    service: string;
    name: string;
    createdAt: bigint;
    email: string;
    projectDetails: string;
}
export interface BlogPostInput {
    postType: PostType;
    title: string;
    featured: boolean;
    content: string;
    slug: string;
    tags: Array<string>;
    imageUrl: string;
    projectId?: bigint;
    excerpt: string;
}
export type ProjectId = bigint;
export interface TestimonialInput {
    featured: boolean;
    clientName: string;
    tags: Array<string>;
    quote: string;
    company: string;
    imageUrl: string;
    projectId?: bigint;
    rating: bigint;
    clientTitle: string;
}
export interface Project {
    id: ProjectId;
    title: string;
    createdAt: bigint;
    description: string;
    imageUrl: string;
    category: string;
    techStack: Array<string>;
}
export type TestimonialId = bigint;
export type SubmissionId = bigint;
export enum PostType {
    caseStudy = "caseStudy",
    standalone = "standalone"
}
export interface backendInterface {
    addBlogPost(input: BlogPostInput): Promise<{
        __kind__: "ok";
        ok: BlogPost;
    } | {
        __kind__: "err";
        err: string;
    }>;
    addProject(input: ProjectInput): Promise<Project>;
    addTestimonial(input: TestimonialInput): Promise<{
        __kind__: "ok";
        ok: Testimonial;
    } | {
        __kind__: "err";
        err: string;
    }>;
    deleteBlogPost(id: bigint): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    deleteProject(id: ProjectId): Promise<boolean>;
    deleteSubmission(id: SubmissionId): Promise<boolean>;
    deleteTestimonial(id: bigint): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    featureBlogPost(id: bigint, featured: boolean): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    featureTestimonial(id: bigint, featured: boolean): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    getBlogPost(slug: string): Promise<BlogPost | null>;
    getBlogPosts(): Promise<Array<BlogPost>>;
    getBlogPostsForProject(projectId: bigint): Promise<Array<BlogPost>>;
    getFeaturedBlogPosts(): Promise<Array<BlogPost>>;
    getFeaturedTestimonials(): Promise<Array<Testimonial>>;
    getProject(id: ProjectId): Promise<Project | null>;
    getProjects(): Promise<Array<Project>>;
    getSubmissions(): Promise<Array<ContactSubmission>>;
    getTestimonials(): Promise<Array<Testimonial>>;
    getTestimonialsForProject(projectId: bigint): Promise<Array<Testimonial>>;
    isAdmin(): Promise<boolean>;
    submitContact(input: ContactInput): Promise<ContactSubmission>;
    updateBlogPost(id: bigint, input: BlogPostInput): Promise<{
        __kind__: "ok";
        ok: BlogPost;
    } | {
        __kind__: "err";
        err: string;
    }>;
    updateProject(id: ProjectId, input: ProjectInput): Promise<Project | null>;
    updateTestimonial(id: bigint, input: TestimonialInput): Promise<{
        __kind__: "ok";
        ok: Testimonial;
    } | {
        __kind__: "err";
        err: string;
    }>;
}
import type { BlogPost as _BlogPost, BlogPostId as _BlogPostId, BlogPostInput as _BlogPostInput, PostType as _PostType, Project as _Project, Testimonial as _Testimonial, TestimonialId as _TestimonialId, TestimonialInput as _TestimonialInput } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addBlogPost(arg0: BlogPostInput): Promise<{
        __kind__: "ok";
        ok: BlogPost;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.addBlogPost(to_candid_BlogPostInput_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid_variant_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addBlogPost(to_candid_BlogPostInput_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid_variant_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async addProject(arg0: ProjectInput): Promise<Project> {
        if (this.processError) {
            try {
                const result = await this.actor.addProject(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addProject(arg0);
            return result;
        }
    }
    async addTestimonial(arg0: TestimonialInput): Promise<{
        __kind__: "ok";
        ok: Testimonial;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.addTestimonial(to_candid_TestimonialInput_n11(this._uploadFile, this._downloadFile, arg0));
                return from_candid_variant_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addTestimonial(to_candid_TestimonialInput_n11(this._uploadFile, this._downloadFile, arg0));
            return from_candid_variant_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteBlogPost(arg0: bigint): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteBlogPost(arg0);
                return from_candid_variant_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteBlogPost(arg0);
            return from_candid_variant_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteProject(arg0: ProjectId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteProject(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteProject(arg0);
            return result;
        }
    }
    async deleteSubmission(arg0: SubmissionId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteSubmission(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteSubmission(arg0);
            return result;
        }
    }
    async deleteTestimonial(arg0: bigint): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteTestimonial(arg0);
                return from_candid_variant_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteTestimonial(arg0);
            return from_candid_variant_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async featureBlogPost(arg0: bigint, arg1: boolean): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.featureBlogPost(arg0, arg1);
                return from_candid_variant_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.featureBlogPost(arg0, arg1);
            return from_candid_variant_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async featureTestimonial(arg0: bigint, arg1: boolean): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.featureTestimonial(arg0, arg1);
                return from_candid_variant_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.featureTestimonial(arg0, arg1);
            return from_candid_variant_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBlogPost(arg0: string): Promise<BlogPost | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getBlogPost(arg0);
                return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBlogPost(arg0);
            return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBlogPosts(): Promise<Array<BlogPost>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBlogPosts();
                return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBlogPosts();
            return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBlogPostsForProject(arg0: bigint): Promise<Array<BlogPost>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBlogPostsForProject(arg0);
                return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBlogPostsForProject(arg0);
            return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFeaturedBlogPosts(): Promise<Array<BlogPost>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFeaturedBlogPosts();
                return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFeaturedBlogPosts();
            return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFeaturedTestimonials(): Promise<Array<Testimonial>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFeaturedTestimonials();
                return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFeaturedTestimonials();
            return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProject(arg0: ProjectId): Promise<Project | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getProject(arg0);
                return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProject(arg0);
            return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProjects(): Promise<Array<Project>> {
        if (this.processError) {
            try {
                const result = await this.actor.getProjects();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProjects();
            return result;
        }
    }
    async getSubmissions(): Promise<Array<ContactSubmission>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSubmissions();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSubmissions();
            return result;
        }
    }
    async getTestimonials(): Promise<Array<Testimonial>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTestimonials();
                return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTestimonials();
            return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTestimonialsForProject(arg0: bigint): Promise<Array<Testimonial>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTestimonialsForProject(arg0);
                return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTestimonialsForProject(arg0);
            return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async isAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isAdmin();
            return result;
        }
    }
    async submitContact(arg0: ContactInput): Promise<ContactSubmission> {
        if (this.processError) {
            try {
                const result = await this.actor.submitContact(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitContact(arg0);
            return result;
        }
    }
    async updateBlogPost(arg0: bigint, arg1: BlogPostInput): Promise<{
        __kind__: "ok";
        ok: BlogPost;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.updateBlogPost(arg0, to_candid_BlogPostInput_n1(this._uploadFile, this._downloadFile, arg1));
                return from_candid_variant_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateBlogPost(arg0, to_candid_BlogPostInput_n1(this._uploadFile, this._downloadFile, arg1));
            return from_candid_variant_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateProject(arg0: ProjectId, arg1: ProjectInput): Promise<Project | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProject(arg0, arg1);
                return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProject(arg0, arg1);
            return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateTestimonial(arg0: bigint, arg1: TestimonialInput): Promise<{
        __kind__: "ok";
        ok: Testimonial;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTestimonial(arg0, to_candid_TestimonialInput_n11(this._uploadFile, this._downloadFile, arg1));
                return from_candid_variant_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTestimonial(arg0, to_candid_TestimonialInput_n11(this._uploadFile, this._downloadFile, arg1));
            return from_candid_variant_n13(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_BlogPost_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BlogPost): BlogPost {
    return from_candid_record_n7(_uploadFile, _downloadFile, value);
}
function from_candid_PostType_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PostType): PostType {
    return from_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function from_candid_Testimonial_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Testimonial): Testimonial {
    return from_candid_record_n15(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_BlogPost]): BlogPost | null {
    return value.length === 0 ? null : from_candid_BlogPost_n6(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Project]): Project | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _TestimonialId;
    featured: boolean;
    clientName: string;
    createdAt: bigint;
    tags: Array<string>;
    quote: string;
    company: string;
    imageUrl: string;
    projectId: [] | [bigint];
    rating: bigint;
    clientTitle: string;
}): {
    id: TestimonialId;
    featured: boolean;
    clientName: string;
    createdAt: bigint;
    tags: Array<string>;
    quote: string;
    company: string;
    imageUrl: string;
    projectId?: bigint;
    rating: bigint;
    clientTitle: string;
} {
    return {
        id: value.id,
        featured: value.featured,
        clientName: value.clientName,
        createdAt: value.createdAt,
        tags: value.tags,
        quote: value.quote,
        company: value.company,
        imageUrl: value.imageUrl,
        projectId: record_opt_to_undefined(from_candid_opt_n10(_uploadFile, _downloadFile, value.projectId)),
        rating: value.rating,
        clientTitle: value.clientTitle
    };
}
function from_candid_record_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _BlogPostId;
    postType: _PostType;
    title: string;
    featured: boolean;
    content: string;
    createdAt: bigint;
    slug: string;
    tags: Array<string>;
    imageUrl: string;
    projectId: [] | [bigint];
    excerpt: string;
}): {
    id: BlogPostId;
    postType: PostType;
    title: string;
    featured: boolean;
    content: string;
    createdAt: bigint;
    slug: string;
    tags: Array<string>;
    imageUrl: string;
    projectId?: bigint;
    excerpt: string;
} {
    return {
        id: value.id,
        postType: from_candid_PostType_n8(_uploadFile, _downloadFile, value.postType),
        title: value.title,
        featured: value.featured,
        content: value.content,
        createdAt: value.createdAt,
        slug: value.slug,
        tags: value.tags,
        imageUrl: value.imageUrl,
        projectId: record_opt_to_undefined(from_candid_opt_n10(_uploadFile, _downloadFile, value.projectId)),
        excerpt: value.excerpt
    };
}
function from_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _Testimonial;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: Testimonial;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_Testimonial_n14(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: null;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _BlogPost;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: BlogPost;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_BlogPost_n6(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    caseStudy: null;
} | {
    standalone: null;
}): PostType {
    return "caseStudy" in value ? PostType.caseStudy : "standalone" in value ? PostType.standalone : value;
}
function from_candid_vec_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_BlogPost>): Array<BlogPost> {
    return value.map((x)=>from_candid_BlogPost_n6(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Testimonial>): Array<Testimonial> {
    return value.map((x)=>from_candid_Testimonial_n14(_uploadFile, _downloadFile, x));
}
function to_candid_BlogPostInput_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BlogPostInput): _BlogPostInput {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_PostType_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PostType): _PostType {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_TestimonialInput_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TestimonialInput): _TestimonialInput {
    return to_candid_record_n12(_uploadFile, _downloadFile, value);
}
function to_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    featured: boolean;
    clientName: string;
    tags: Array<string>;
    quote: string;
    company: string;
    imageUrl: string;
    projectId?: bigint;
    rating: bigint;
    clientTitle: string;
}): {
    featured: boolean;
    clientName: string;
    tags: Array<string>;
    quote: string;
    company: string;
    imageUrl: string;
    projectId: [] | [bigint];
    rating: bigint;
    clientTitle: string;
} {
    return {
        featured: value.featured,
        clientName: value.clientName,
        tags: value.tags,
        quote: value.quote,
        company: value.company,
        imageUrl: value.imageUrl,
        projectId: value.projectId ? candid_some(value.projectId) : candid_none(),
        rating: value.rating,
        clientTitle: value.clientTitle
    };
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    postType: PostType;
    title: string;
    featured: boolean;
    content: string;
    slug: string;
    tags: Array<string>;
    imageUrl: string;
    projectId?: bigint;
    excerpt: string;
}): {
    postType: _PostType;
    title: string;
    featured: boolean;
    content: string;
    slug: string;
    tags: Array<string>;
    imageUrl: string;
    projectId: [] | [bigint];
    excerpt: string;
} {
    return {
        postType: to_candid_PostType_n3(_uploadFile, _downloadFile, value.postType),
        title: value.title,
        featured: value.featured,
        content: value.content,
        slug: value.slug,
        tags: value.tags,
        imageUrl: value.imageUrl,
        projectId: value.projectId ? candid_some(value.projectId) : candid_none(),
        excerpt: value.excerpt
    };
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PostType): {
    caseStudy: null;
} | {
    standalone: null;
} {
    return value == PostType.caseStudy ? {
        caseStudy: null
    } : value == PostType.standalone ? {
        standalone: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
